@startuml


state 01_Application {
[*] --> Transient

Transient -> 02_Loaded:(icon is loaded)
Transient -> Loading:(icon not loaded)

Loading -> Transient:load icon

state 02_Loaded {
[*] -> 03_ListingFeedScreen

}

}


@enduml